spring.application.name=exp-15_backend

server.port=8080

spring.datasource.url=jdbc:h2:mem:exp15db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

app.jwt.secret=1f16c9b4f7119ea10215f58b6e4dc49fa8f35d016fdb7d8e242f124a08993f1d
app.jwt.expiration-ms=3600000
